def display_pattern(strip):
    pixelcount = strip.numPixels()
    def changeallthepixels(color):
        for pixel in range(pixelcount):
            strip.setPixelColor(pixel, color)
    changeallthepixels(Color(0,0,16))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,0,32))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,0,48))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,0,64))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,0,80))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,16,0))
    strip.show()
    time.sleep(.5)
    changeallthepixels(Color(0,32,0))
    strip.show()
    time.sleep(.5)
